### ISSUE TITLE
Navigating back, then forward, from a job configuration causes loss of config data in Chrome

### ISSUE THREAD

**Issue by omehegan** [imod/conditional-buildstep-plugin#1]
1. Open a job configuration that has a conditional build step defined in it, with the Chrome browser (Firefox does not show this problem).
2. Click the back button to navigate away from the config.
3. Click forward to go back to the config.
4. The conditional build step settings will be blank/default, but all other job configuration remains correct.
   This is a really nasty bug, I've had a number of users accidentally break their configs without realizing it, because if you save after this happens you lose the conditional build step settings. Luckily the Job Config History plugin makes it easy for us to undo this.

This is also filed as JENKINS-18435.

**Comment by imod** [comment]
we don't trak Bugs in GH issues, we wana keep all info togather in JIRA which makes it easter for Users to find the stuff
As you have created the Same issue in JIRA already, i'm closing thi one
